add email sending
nikitakoliadin/knubisoft-pirozochki pull request #10
Opened 2023-05-14 23:23 UTC by kolesnykv

2023-05-15 04:45 UTC, nikitakoliadin commented on application/src/main/java/com/knubisoft/application/service/EmailServiceImpl.java
> +            return "Error while Sending Mail";
Pls log an error.

2023-05-15 04:45 UTC, nikitakoliadin commented on application/src/main/java/com/knubisoft/application/service/EmailServiceImpl.java
> +            return "Error while sending mail!!!";
The same

2023-05-15 04:45 UTC, nikitakoliadin commented on application/src/main/resources/application.properties
> +spring.mail.password=tufbvcsmvrhmkuwk
Nice password :D

2023-05-15 04:45 UTC, nikitakoliadin commented on application/src/main/resources/application.properties
> +spring.mail.password=tufbvcsmvrhmkuwk
Pls do research how to hide it.
For example you can encrypt it.

2023-05-16 15:44 UTC, Nimikin commented on application/src/main/java/com/knubisoft/application/entity/EmailDetails.java
> +    private String attachment;
Do you want to implement List of attachments and restrict it by 3 files per message, something like that?

2023-05-26 08:23 UTC, nikitakoliadin requested changes
Waiting the tests

2023-05-30 09:03 UTC, nikitakoliadin approved these changes

2023-05-31 13:24 UTC, nikitashumsky commented on application/src/main/java/com/knubisoft/application/service/EmailServiceImpl.java
> +            + "Message will be sent will be sent without it.";
"will be sent" repeats 2 times

2023-05-31 13:26 UTC, Nimikin approved these changes

2023-05-31 13:48 UTC, nikitakoliadin approved these changes

2023-05-31 13:53 UTC, connor999jobs approved these changes

2023-05-31 18:37 UTC, nikitashumsky commented on application/src/main/java/com/knubisoft/application/service/EmailServiceImpl.java
> +        for (String attachment : emailDetails.getAttachments().subList(0, (attachmentsCapSize - 1))) {
sublist already doing (attachmentsCapSize - 1), cause he excludes the last index. Now we're getting 2\3 attachments when sending 3

2023-06-01 04:42 UTC, merged